stages:
  - install
  - lint
  - test
  - build
  - package
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:20
  script:
    # Try npm ci if lockfile exists, otherwise npm install
    - if [ -f package-lock.json ]; then npm ci; else npm install; fi

lint:
  stage: lint
  image: node:20
  script:
    - npm run lint || echo "No linting configured"
    - npm run prettier:check || echo "No prettier configured"

test:
  stage: test
  image: node:20
  script:
    - npm test || echo "No tests configured"

build:
  stage: build
  image: node:20
  script:
    - npm run build || echo "No build script configured"
  artifacts:
    paths:
      - dist/

package:
  stage: package
  image: node:20
  script:
    - zip -r extension.zip dist/
  artifacts:
    paths:
      - extension.zip

deploy:
  stage: deploy
  image: node:20
  only:
    - main
  script:
    - echo "Here you could run Chrome Web Store upload"
