# pipeline stages
stages:
  - validate
  - build

# Validate manifest.json
validate-manifest:
  stage: validate
  image: node:18
  before_script:
    - apt-get update && apt-get install -y jq
  script:
    - echo "Validating manifest.json..."
    - cat manifest.json | jq . > /dev/null # checks if JSON is valid
  only: # The job will only run when changes are pushed to the main branch
    - main

# Build zip package
build-extension:
  stage: build
  image: alpine:latest
  before_script:
    - apk add --no-cache zip jq 
  script:
    - mkdir -p dist
    - zip -r dist/youtube-reminder.zip . # Recursively zip all of the files in the folder
  artifacts:
    paths:
      - dist/youtube-reminder.zip
    expire_in: "30 days"
  only:
    - main
# git testing